//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrilliantWMS.ProductCategoryService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductCategoryService.iProductCategoryMaster")]
    public interface iProductCategoryMaster {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/GetProductCategoryList", ReplyAction="http://tempuri.org/iProductCategoryMaster/GetProductCategoryListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        BrilliantWMS.ProductCategoryService.vGetProductCagetoryList[] GetProductCategoryList(string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/InsertmProductCategory", ReplyAction="http://tempuri.org/iProductCategoryMaster/InsertmProductCategoryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        int InsertmProductCategory(BrilliantWMS.ProductCategoryService.mProductCategory prdCategory, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/updatemProductCategory", ReplyAction="http://tempuri.org/iProductCategoryMaster/updatemProductCategoryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        int updatemProductCategory(BrilliantWMS.ProductCategoryService.mProductCategory updatePrdCategory, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/GetProductCategoryListByID", ReplyAction="http://tempuri.org/iProductCategoryMaster/GetProductCategoryListByIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        BrilliantWMS.ProductCategoryService.mProductCategory GetProductCategoryListByID(int prdCategoryId, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/checkDuplicateRecord", ReplyAction="http://tempuri.org/iProductCategoryMaster/checkDuplicateRecordResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        string checkDuplicateRecord(string prdCategoryName, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/checkDuplicateRecordEdit", ReplyAction="http://tempuri.org/iProductCategoryMaster/checkDuplicateRecordEditResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        string checkDuplicateRecordEdit(string prdCategoryName, int prdCategoryID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/GetPrdCategoryRecordToBindGrid", ReplyAction="http://tempuri.org/iProductCategoryMaster/GetPrdCategoryRecordToBindGridResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        System.Data.DataSet GetPrdCategoryRecordToBindGrid(string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/GetProductCategoryListForAsset", ReplyAction="http://tempuri.org/iProductCategoryMaster/GetProductCategoryListForAssetResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        BrilliantWMS.ProductCategoryService.vGetProductCagetoryList[] GetProductCategoryListForAsset(string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/GetActivityList", ReplyAction="http://tempuri.org/iProductCategoryMaster/GetActivityListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        BrilliantWMS.ProductCategoryService.mDropdownValue[] GetActivityList(string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/GetMessageList", ReplyAction="http://tempuri.org/iProductCategoryMaster/GetMessageListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        BrilliantWMS.ProductCategoryService.mDropdownValue[] GetMessageList(string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/InsertEmailTemplate", ReplyAction="http://tempuri.org/iProductCategoryMaster/InsertEmailTemplateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        long InsertEmailTemplate(BrilliantWMS.ProductCategoryService.mMessageEMailTemplate Template, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/GetTemplateListForGrid", ReplyAction="http://tempuri.org/iProductCategoryMaster/GetTemplateListForGridResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        BrilliantWMS.ProductCategoryService.vGetTemplateList1[] GetTemplateListForGrid(string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/UpdateEmailTemplate", ReplyAction="http://tempuri.org/iProductCategoryMaster/UpdateEmailTemplateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        void UpdateEmailTemplate(string ID, string MailSubject, string MailBody, long ModifiedBy, long CompanyID, long DepartmentID, long ActivityID, long MessageID, string TemplateTitle, string Active, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/GetAutoCancellationStatus", ReplyAction="http://tempuri.org/iProductCategoryMaster/GetAutoCancellationStatusResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        string GetAutoCancellationStatus(long DeptID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/checkDuplicateTemplate", ReplyAction="http://tempuri.org/iProductCategoryMaster/checkDuplicateTemplateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        string checkDuplicateTemplate(long company, long Department, long activity, long MessageType, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/checkDuplicateTemplateEdit", ReplyAction="http://tempuri.org/iProductCategoryMaster/checkDuplicateTemplateEditResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        string checkDuplicateTemplateEdit(long TemplateID, long company, long Department, long activity, long MessageType, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/checkDuplicateInterface", ReplyAction="http://tempuri.org/iProductCategoryMaster/checkDuplicateInterfaceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        string checkDuplicateInterface(string Tablename, string FieldName, string DataType, string IsNull, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/checkDuplicateInterfaceEdit", ReplyAction="http://tempuri.org/iProductCategoryMaster/checkDuplicateInterfaceEditResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        string checkDuplicateInterfaceEdit(long ID, string Tablename, string FieldName, string DataType, string IsNull, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/GetDestination", ReplyAction="http://tempuri.org/iProductCategoryMaster/GetDestinationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        BrilliantWMS.ProductCategoryService.mDropdownValue[] GetDestination(string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/GetActionType", ReplyAction="http://tempuri.org/iProductCategoryMaster/GetActionTypeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        BrilliantWMS.ProductCategoryService.mDropdownValue[] GetActionType(string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/GetObject", ReplyAction="http://tempuri.org/iProductCategoryMaster/GetObjectResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        BrilliantWMS.ProductCategoryService.mDropdownValue[] GetObject(string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/FieldList", ReplyAction="http://tempuri.org/iProductCategoryMaster/FieldListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        BrilliantWMS.ProductCategoryService.mInterfaceMap[] FieldList(string TableName, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/InsertMessageIntoTemptable", ReplyAction="http://tempuri.org/iProductCategoryMaster/InsertMessageIntoTemptableResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        void InsertMessageIntoTemptable(string Title, string Destination, string Type, string Purpose, string Object1, long Field1, long Sequence, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/DeleteMessageTemptable", ReplyAction="http://tempuri.org/iProductCategoryMaster/DeleteMessageTemptableResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        void DeleteMessageTemptable(string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/InsertMessageHeader", ReplyAction="http://tempuri.org/iProductCategoryMaster/InsertMessageHeaderResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        void InsertMessageHeader(string Destination, string ActionType, string TableName, string description, long CreatedBy, string Remark, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/GetMessHeaderID", ReplyAction="http://tempuri.org/iProductCategoryMaster/GetMessHeaderIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        System.Data.DataSet GetMessHeaderID(string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/InsrtIntoMessageHeader", ReplyAction="http://tempuri.org/iProductCategoryMaster/InsrtIntoMessageHeaderResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        void InsrtIntoMessageHeader(long HeaderId, long Sequence, long FieldID, long CreatedBy, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/GetMessageTempData", ReplyAction="http://tempuri.org/iProductCategoryMaster/GetMessageTempDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        System.Data.DataSet GetMessageTempData(string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/GetFieldDetails", ReplyAction="http://tempuri.org/iProductCategoryMaster/GetFieldDetailsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        System.Data.DataSet GetFieldDetails(string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/DeleteFieldFromList", ReplyAction="http://tempuri.org/iProductCategoryMaster/DeleteFieldFromListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        void DeleteFieldFromList(long ID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/DeleteFieldFromListWhenEdit", ReplyAction="http://tempuri.org/iProductCategoryMaster/DeleteFieldFromListWhenEditResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        void DeleteFieldFromListWhenEdit(long ID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/GetFieldDetailsFromMessageTable", ReplyAction="http://tempuri.org/iProductCategoryMaster/GetFieldDetailsFromMessageTableResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        System.Data.DataSet GetFieldDetailsFromMessageTable(long MessageID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/UpdateMessageHeader", ReplyAction="http://tempuri.org/iProductCategoryMaster/UpdateMessageHeaderResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        void UpdateMessageHeader(long MessageheaderID, string Destination, string ActionType, string TableName, string description, long ModifyBy, string Remark, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/InsertMessageDetails", ReplyAction="http://tempuri.org/iProductCategoryMaster/InsertMessageDetailsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        void InsertMessageDetails(long MsgHeadID, long Field, long Sequence, long CreatedBy, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/GetTemplateListForGridAdmin", ReplyAction="http://tempuri.org/iProductCategoryMaster/GetTemplateListForGridAdminResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        BrilliantWMS.ProductCategoryService.vGetTemplateList1[] GetTemplateListForGridAdmin(long UserID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/GetCustomerList", ReplyAction="http://tempuri.org/iProductCategoryMaster/GetCustomerListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        BrilliantWMS.ProductCategoryService.V_WMS_ProductCategory[] GetCustomerList(string[] conn);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class vGetProductCagetoryList : EntityObject {
        
        private long idField;
        
        private string productCategoryField;
        
        private System.Nullable<long> sequenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ProductCategory {
            get {
                return this.productCategoryField;
            }
            set {
                this.productCategoryField = value;
                this.RaisePropertyChanged("ProductCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<long> Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
                this.RaisePropertyChanged("Sequence");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mMessageEMailTemplate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mProductCategory))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(V_WMS_ProductCategory))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mInterfaceMap))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(vGetTemplateList1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mDropdownValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(vGetProductCagetoryList))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class EntityObject : StructuralObject {
        
        private EntityKey entityKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EntityKey EntityKey {
            get {
                return this.entityKeyField;
            }
            set {
                this.entityKeyField = value;
                this.RaisePropertyChanged("EntityKey");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityKey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entitySetNameField;
        
        private string entityContainerNameField;
        
        private EntityKeyMember[] entityKeyValuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EntitySetName {
            get {
                return this.entitySetNameField;
            }
            set {
                this.entitySetNameField = value;
                this.RaisePropertyChanged("EntitySetName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EntityContainerName {
            get {
                return this.entityContainerNameField;
            }
            set {
                this.entityContainerNameField = value;
                this.RaisePropertyChanged("EntityContainerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public EntityKeyMember[] EntityKeyValues {
            get {
                return this.entityKeyValuesField;
            }
            set {
                this.entityKeyValuesField = value;
                this.RaisePropertyChanged("EntityKeyValues");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityKeyMember : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private object valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mMessageEMailTemplate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mProductCategory))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(V_WMS_ProductCategory))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mInterfaceMap))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(vGetTemplateList1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mDropdownValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(vGetProductCagetoryList))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class StructuralObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class mMessageEMailTemplate : EntityObject {
        
        private long idField;
        
        private string objectNameField;
        
        private System.Nullable<long> mStatusIDField;
        
        private string mailTypeField;
        
        private string mailSubjectField;
        
        private string mailBodyField;
        
        private string activeField;
        
        private System.Nullable<long> createdByField;
        
        private System.Nullable<System.DateTime> creationDateField;
        
        private System.Nullable<System.DateTime> modifiedDateField;
        
        private System.Nullable<long> modifiedByField;
        
        private System.Nullable<long> companyIDField;
        
        private System.Nullable<long> departmentIDField;
        
        private System.Nullable<long> activityIDField;
        
        private System.Nullable<long> messageIDField;
        
        private string templateTitleField;
        
        private string mobileTextField;
        
        private System.Nullable<long> customerIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
                this.RaisePropertyChanged("ObjectName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<long> mStatusID {
            get {
                return this.mStatusIDField;
            }
            set {
                this.mStatusIDField = value;
                this.RaisePropertyChanged("mStatusID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MailType {
            get {
                return this.mailTypeField;
            }
            set {
                this.mailTypeField = value;
                this.RaisePropertyChanged("MailType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MailSubject {
            get {
                return this.mailSubjectField;
            }
            set {
                this.mailSubjectField = value;
                this.RaisePropertyChanged("MailSubject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string MailBody {
            get {
                return this.mailBodyField;
            }
            set {
                this.mailBodyField = value;
                this.RaisePropertyChanged("MailBody");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<long> CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<System.DateTime> CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
                this.RaisePropertyChanged("CreationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<System.DateTime> ModifiedDate {
            get {
                return this.modifiedDateField;
            }
            set {
                this.modifiedDateField = value;
                this.RaisePropertyChanged("ModifiedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<long> ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
                this.RaisePropertyChanged("ModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<long> CompanyID {
            get {
                return this.companyIDField;
            }
            set {
                this.companyIDField = value;
                this.RaisePropertyChanged("CompanyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<long> DepartmentID {
            get {
                return this.departmentIDField;
            }
            set {
                this.departmentIDField = value;
                this.RaisePropertyChanged("DepartmentID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<long> ActivityID {
            get {
                return this.activityIDField;
            }
            set {
                this.activityIDField = value;
                this.RaisePropertyChanged("ActivityID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<long> MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
                this.RaisePropertyChanged("MessageID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string TemplateTitle {
            get {
                return this.templateTitleField;
            }
            set {
                this.templateTitleField = value;
                this.RaisePropertyChanged("TemplateTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string MobileText {
            get {
                return this.mobileTextField;
            }
            set {
                this.mobileTextField = value;
                this.RaisePropertyChanged("MobileText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<long> CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("CustomerID");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class mProductCategory : EntityObject {
        
        private long idField;
        
        private string nameField;
        
        private System.Nullable<long> sequenceField;
        
        private string activeField;
        
        private string createdByField;
        
        private System.DateTime creationDateField;
        
        private string lastModifiedByField;
        
        private System.Nullable<System.DateTime> lastModifiedDateField;
        
        private long companyIDField;
        
        private System.Nullable<long> customerIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<long> Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
                this.RaisePropertyChanged("Sequence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
                this.RaisePropertyChanged("CreationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string LastModifiedBy {
            get {
                return this.lastModifiedByField;
            }
            set {
                this.lastModifiedByField = value;
                this.RaisePropertyChanged("LastModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<System.DateTime> LastModifiedDate {
            get {
                return this.lastModifiedDateField;
            }
            set {
                this.lastModifiedDateField = value;
                this.RaisePropertyChanged("LastModifiedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public long CompanyID {
            get {
                return this.companyIDField;
            }
            set {
                this.companyIDField = value;
                this.RaisePropertyChanged("CompanyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<long> CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("CustomerID");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class V_WMS_ProductCategory : EntityObject {
        
        private long idField;
        
        private string categoryField;
        
        private System.Nullable<long> sequenceField;
        
        private string activeField;
        
        private string companyField;
        
        private string customerField;
        
        private long companyIDField;
        
        private System.Nullable<long> customerIDField;
        
        private System.Nullable<long> userIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("Category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<long> Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
                this.RaisePropertyChanged("Sequence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("Company");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
                this.RaisePropertyChanged("Customer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long CompanyID {
            get {
                return this.companyIDField;
            }
            set {
                this.companyIDField = value;
                this.RaisePropertyChanged("CompanyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<long> CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("CustomerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<long> UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class mInterfaceMap : EntityObject {
        
        private long idField;
        
        private string fieldnameField;
        
        private string fieldDataTypeField;
        
        private string isNullField;
        
        private string tableNameField;
        
        private string descriptionField;
        
        private System.Nullable<long> createdByField;
        
        private System.Nullable<System.DateTime> creationDateField;
        
        private System.Nullable<long> modifyByField;
        
        private System.Nullable<System.DateTime> modifyDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Fieldname {
            get {
                return this.fieldnameField;
            }
            set {
                this.fieldnameField = value;
                this.RaisePropertyChanged("Fieldname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FieldDataType {
            get {
                return this.fieldDataTypeField;
            }
            set {
                this.fieldDataTypeField = value;
                this.RaisePropertyChanged("FieldDataType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string IsNull {
            get {
                return this.isNullField;
            }
            set {
                this.isNullField = value;
                this.RaisePropertyChanged("IsNull");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
                this.RaisePropertyChanged("TableName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<long> CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<System.DateTime> CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
                this.RaisePropertyChanged("CreationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<long> ModifyBy {
            get {
                return this.modifyByField;
            }
            set {
                this.modifyByField = value;
                this.RaisePropertyChanged("ModifyBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<System.DateTime> ModifyDate {
            get {
                return this.modifyDateField;
            }
            set {
                this.modifyDateField = value;
                this.RaisePropertyChanged("ModifyDate");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class vGetTemplateList1 : EntityObject {
        
        private long idField;
        
        private string mailSubjectField;
        
        private string mailBodyField;
        
        private string activeField;
        
        private System.Nullable<long> companyIDField;
        
        private string companyNameField;
        
        private string territoryField;
        
        private System.Nullable<long> departmentIDField;
        
        private System.Nullable<long> activityIDField;
        
        private string activityField;
        
        private System.Nullable<long> messageIDField;
        
        private string messageTypeField;
        
        private string templateTitleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MailSubject {
            get {
                return this.mailSubjectField;
            }
            set {
                this.mailSubjectField = value;
                this.RaisePropertyChanged("MailSubject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MailBody {
            get {
                return this.mailBodyField;
            }
            set {
                this.mailBodyField = value;
                this.RaisePropertyChanged("MailBody");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<long> CompanyID {
            get {
                return this.companyIDField;
            }
            set {
                this.companyIDField = value;
                this.RaisePropertyChanged("CompanyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
                this.RaisePropertyChanged("CompanyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Territory {
            get {
                return this.territoryField;
            }
            set {
                this.territoryField = value;
                this.RaisePropertyChanged("Territory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<long> DepartmentID {
            get {
                return this.departmentIDField;
            }
            set {
                this.departmentIDField = value;
                this.RaisePropertyChanged("DepartmentID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<long> ActivityID {
            get {
                return this.activityIDField;
            }
            set {
                this.activityIDField = value;
                this.RaisePropertyChanged("ActivityID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Activity {
            get {
                return this.activityField;
            }
            set {
                this.activityField = value;
                this.RaisePropertyChanged("Activity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<long> MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
                this.RaisePropertyChanged("MessageID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string MessageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
                this.RaisePropertyChanged("MessageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string TemplateTitle {
            get {
                return this.templateTitleField;
            }
            set {
                this.templateTitleField = value;
                this.RaisePropertyChanged("TemplateTitle");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class mDropdownValue : EntityObject {
        
        private int idField;
        
        private string valueField;
        
        private string parameterField;
        
        private System.Nullable<long> statusIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
                this.RaisePropertyChanged("Parameter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<long> StatusID {
            get {
                return this.statusIDField;
            }
            set {
                this.statusIDField = value;
                this.RaisePropertyChanged("StatusID");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface iProductCategoryMasterChannel : BrilliantWMS.ProductCategoryService.iProductCategoryMaster, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class iProductCategoryMasterClient : System.ServiceModel.ClientBase<BrilliantWMS.ProductCategoryService.iProductCategoryMaster>, BrilliantWMS.ProductCategoryService.iProductCategoryMaster {
        
        public iProductCategoryMasterClient() {
        }
        
        public iProductCategoryMasterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public iProductCategoryMasterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iProductCategoryMasterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iProductCategoryMasterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BrilliantWMS.ProductCategoryService.vGetProductCagetoryList[] GetProductCategoryList(string[] conn) {
            return base.Channel.GetProductCategoryList(conn);
        }
        
        public int InsertmProductCategory(BrilliantWMS.ProductCategoryService.mProductCategory prdCategory, string[] conn) {
            return base.Channel.InsertmProductCategory(prdCategory, conn);
        }
        
        public int updatemProductCategory(BrilliantWMS.ProductCategoryService.mProductCategory updatePrdCategory, string[] conn) {
            return base.Channel.updatemProductCategory(updatePrdCategory, conn);
        }
        
        public BrilliantWMS.ProductCategoryService.mProductCategory GetProductCategoryListByID(int prdCategoryId, string[] conn) {
            return base.Channel.GetProductCategoryListByID(prdCategoryId, conn);
        }
        
        public string checkDuplicateRecord(string prdCategoryName, string[] conn) {
            return base.Channel.checkDuplicateRecord(prdCategoryName, conn);
        }
        
        public string checkDuplicateRecordEdit(string prdCategoryName, int prdCategoryID, string[] conn) {
            return base.Channel.checkDuplicateRecordEdit(prdCategoryName, prdCategoryID, conn);
        }
        
        public System.Data.DataSet GetPrdCategoryRecordToBindGrid(string[] conn) {
            return base.Channel.GetPrdCategoryRecordToBindGrid(conn);
        }
        
        public BrilliantWMS.ProductCategoryService.vGetProductCagetoryList[] GetProductCategoryListForAsset(string[] conn) {
            return base.Channel.GetProductCategoryListForAsset(conn);
        }
        
        public BrilliantWMS.ProductCategoryService.mDropdownValue[] GetActivityList(string[] conn) {
            return base.Channel.GetActivityList(conn);
        }
        
        public BrilliantWMS.ProductCategoryService.mDropdownValue[] GetMessageList(string[] conn) {
            return base.Channel.GetMessageList(conn);
        }
        
        public long InsertEmailTemplate(BrilliantWMS.ProductCategoryService.mMessageEMailTemplate Template, string[] conn) {
            return base.Channel.InsertEmailTemplate(Template, conn);
        }
        
        public BrilliantWMS.ProductCategoryService.vGetTemplateList1[] GetTemplateListForGrid(string[] conn) {
            return base.Channel.GetTemplateListForGrid(conn);
        }
        
        public void UpdateEmailTemplate(string ID, string MailSubject, string MailBody, long ModifiedBy, long CompanyID, long DepartmentID, long ActivityID, long MessageID, string TemplateTitle, string Active, string[] conn) {
            base.Channel.UpdateEmailTemplate(ID, MailSubject, MailBody, ModifiedBy, CompanyID, DepartmentID, ActivityID, MessageID, TemplateTitle, Active, conn);
        }
        
        public string GetAutoCancellationStatus(long DeptID, string[] conn) {
            return base.Channel.GetAutoCancellationStatus(DeptID, conn);
        }
        
        public string checkDuplicateTemplate(long company, long Department, long activity, long MessageType, string[] conn) {
            return base.Channel.checkDuplicateTemplate(company, Department, activity, MessageType, conn);
        }
        
        public string checkDuplicateTemplateEdit(long TemplateID, long company, long Department, long activity, long MessageType, string[] conn) {
            return base.Channel.checkDuplicateTemplateEdit(TemplateID, company, Department, activity, MessageType, conn);
        }
        
        public string checkDuplicateInterface(string Tablename, string FieldName, string DataType, string IsNull, string[] conn) {
            return base.Channel.checkDuplicateInterface(Tablename, FieldName, DataType, IsNull, conn);
        }
        
        public string checkDuplicateInterfaceEdit(long ID, string Tablename, string FieldName, string DataType, string IsNull, string[] conn) {
            return base.Channel.checkDuplicateInterfaceEdit(ID, Tablename, FieldName, DataType, IsNull, conn);
        }
        
        public BrilliantWMS.ProductCategoryService.mDropdownValue[] GetDestination(string[] conn) {
            return base.Channel.GetDestination(conn);
        }
        
        public BrilliantWMS.ProductCategoryService.mDropdownValue[] GetActionType(string[] conn) {
            return base.Channel.GetActionType(conn);
        }
        
        public BrilliantWMS.ProductCategoryService.mDropdownValue[] GetObject(string[] conn) {
            return base.Channel.GetObject(conn);
        }
        
        public BrilliantWMS.ProductCategoryService.mInterfaceMap[] FieldList(string TableName, string[] conn) {
            return base.Channel.FieldList(TableName, conn);
        }
        
        public void InsertMessageIntoTemptable(string Title, string Destination, string Type, string Purpose, string Object1, long Field1, long Sequence, string[] conn) {
            base.Channel.InsertMessageIntoTemptable(Title, Destination, Type, Purpose, Object1, Field1, Sequence, conn);
        }
        
        public void DeleteMessageTemptable(string[] conn) {
            base.Channel.DeleteMessageTemptable(conn);
        }
        
        public void InsertMessageHeader(string Destination, string ActionType, string TableName, string description, long CreatedBy, string Remark, string[] conn) {
            base.Channel.InsertMessageHeader(Destination, ActionType, TableName, description, CreatedBy, Remark, conn);
        }
        
        public System.Data.DataSet GetMessHeaderID(string[] conn) {
            return base.Channel.GetMessHeaderID(conn);
        }
        
        public void InsrtIntoMessageHeader(long HeaderId, long Sequence, long FieldID, long CreatedBy, string[] conn) {
            base.Channel.InsrtIntoMessageHeader(HeaderId, Sequence, FieldID, CreatedBy, conn);
        }
        
        public System.Data.DataSet GetMessageTempData(string[] conn) {
            return base.Channel.GetMessageTempData(conn);
        }
        
        public System.Data.DataSet GetFieldDetails(string[] conn) {
            return base.Channel.GetFieldDetails(conn);
        }
        
        public void DeleteFieldFromList(long ID, string[] conn) {
            base.Channel.DeleteFieldFromList(ID, conn);
        }
        
        public void DeleteFieldFromListWhenEdit(long ID, string[] conn) {
            base.Channel.DeleteFieldFromListWhenEdit(ID, conn);
        }
        
        public System.Data.DataSet GetFieldDetailsFromMessageTable(long MessageID, string[] conn) {
            return base.Channel.GetFieldDetailsFromMessageTable(MessageID, conn);
        }
        
        public void UpdateMessageHeader(long MessageheaderID, string Destination, string ActionType, string TableName, string description, long ModifyBy, string Remark, string[] conn) {
            base.Channel.UpdateMessageHeader(MessageheaderID, Destination, ActionType, TableName, description, ModifyBy, Remark, conn);
        }
        
        public void InsertMessageDetails(long MsgHeadID, long Field, long Sequence, long CreatedBy, string[] conn) {
            base.Channel.InsertMessageDetails(MsgHeadID, Field, Sequence, CreatedBy, conn);
        }
        
        public BrilliantWMS.ProductCategoryService.vGetTemplateList1[] GetTemplateListForGridAdmin(long UserID, string[] conn) {
            return base.Channel.GetTemplateListForGridAdmin(UserID, conn);
        }
        
        public BrilliantWMS.ProductCategoryService.V_WMS_ProductCategory[] GetCustomerList(string[] conn) {
            return base.Channel.GetCustomerList(conn);
        }
    }
}
