//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Interface.AddToCart
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BISPL_CRMDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BISPL_CRMDBEntities object using the connection string found in the 'BISPL_CRMDBEntities' section of the application configuration file.
        /// </summary>
        public BISPL_CRMDBEntities() : base("name=BISPL_CRMDBEntities", "BISPL_CRMDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BISPL_CRMDBEntities object.
        /// </summary>
        public BISPL_CRMDBEntities(string connectionString) : base(connectionString, "BISPL_CRMDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BISPL_CRMDBEntities object.
        /// </summary>
        public BISPL_CRMDBEntities(EntityConnection connection) : base(connection, "BISPL_CRMDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TempData> TempDatas
        {
            get
            {
                if ((_TempDatas == null))
                {
                    _TempDatas = base.CreateObjectSet<TempData>("TempDatas");
                }
                return _TempDatas;
            }
        }
        private ObjectSet<TempData> _TempDatas;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TempDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTempDatas(TempData tempData)
        {
            base.AddObject("TempDatas", tempData);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="sessionID">No Metadata Documentation available.</param>
        /// <param name="referenceID">No Metadata Documentation available.</param>
        /// <param name="userID">No Metadata Documentation available.</param>
        /// <param name="currentObjectName">No Metadata Documentation available.</param>
        public int SP_InsertIntoCartProductDetail(global::System.String sessionID, Nullable<global::System.Int64> referenceID, global::System.String userID, global::System.String currentObjectName)
        {
            ObjectParameter sessionIDParameter;
            if (sessionID != null)
            {
                sessionIDParameter = new ObjectParameter("SessionID", sessionID);
            }
            else
            {
                sessionIDParameter = new ObjectParameter("SessionID", typeof(global::System.String));
            }
    
            ObjectParameter referenceIDParameter;
            if (referenceID.HasValue)
            {
                referenceIDParameter = new ObjectParameter("ReferenceID", referenceID);
            }
            else
            {
                referenceIDParameter = new ObjectParameter("ReferenceID", typeof(global::System.Int64));
            }
    
            ObjectParameter userIDParameter;
            if (userID != null)
            {
                userIDParameter = new ObjectParameter("UserID", userID);
            }
            else
            {
                userIDParameter = new ObjectParameter("UserID", typeof(global::System.String));
            }
    
            ObjectParameter currentObjectNameParameter;
            if (currentObjectName != null)
            {
                currentObjectNameParameter = new ObjectParameter("CurrentObjectName", currentObjectName);
            }
            else
            {
                currentObjectNameParameter = new ObjectParameter("CurrentObjectName", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("SP_InsertIntoCartProductDetail", sessionIDParameter, referenceIDParameter, userIDParameter, currentObjectNameParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="productIDs">No Metadata Documentation available.</param>
        /// <param name="maxSeqence">No Metadata Documentation available.</param>
        /// <param name="sessionID">No Metadata Documentation available.</param>
        /// <param name="currentObjectName">No Metadata Documentation available.</param>
        /// <param name="referenceID">No Metadata Documentation available.</param>
        /// <param name="objectConvertFrom">No Metadata Documentation available.</param>
        public ObjectResult<SP_GetCartProductDetail_Result> SP_GetCartProductDetail(global::System.String productIDs, Nullable<global::System.Int64> maxSeqence, global::System.String sessionID, global::System.String currentObjectName, Nullable<global::System.Int64> referenceID, global::System.String objectConvertFrom)
        {
            ObjectParameter productIDsParameter;
            if (productIDs != null)
            {
                productIDsParameter = new ObjectParameter("ProductIDs", productIDs);
            }
            else
            {
                productIDsParameter = new ObjectParameter("ProductIDs", typeof(global::System.String));
            }
    
            ObjectParameter maxSeqenceParameter;
            if (maxSeqence.HasValue)
            {
                maxSeqenceParameter = new ObjectParameter("MaxSeqence", maxSeqence);
            }
            else
            {
                maxSeqenceParameter = new ObjectParameter("MaxSeqence", typeof(global::System.Int64));
            }
    
            ObjectParameter sessionIDParameter;
            if (sessionID != null)
            {
                sessionIDParameter = new ObjectParameter("SessionID", sessionID);
            }
            else
            {
                sessionIDParameter = new ObjectParameter("SessionID", typeof(global::System.String));
            }
    
            ObjectParameter currentObjectNameParameter;
            if (currentObjectName != null)
            {
                currentObjectNameParameter = new ObjectParameter("CurrentObjectName", currentObjectName);
            }
            else
            {
                currentObjectNameParameter = new ObjectParameter("CurrentObjectName", typeof(global::System.String));
            }
    
            ObjectParameter referenceIDParameter;
            if (referenceID.HasValue)
            {
                referenceIDParameter = new ObjectParameter("ReferenceID", referenceID);
            }
            else
            {
                referenceIDParameter = new ObjectParameter("ReferenceID", typeof(global::System.Int64));
            }
    
            ObjectParameter objectConvertFromParameter;
            if (objectConvertFrom != null)
            {
                objectConvertFromParameter = new ObjectParameter("ObjectConvertFrom", objectConvertFrom);
            }
            else
            {
                objectConvertFromParameter = new ObjectParameter("ObjectConvertFrom", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<SP_GetCartProductDetail_Result>("SP_GetCartProductDetail", productIDsParameter, maxSeqenceParameter, sessionIDParameter, currentObjectNameParameter, referenceIDParameter, objectConvertFromParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="productIDs">No Metadata Documentation available.</param>
        /// <param name="maxSeqence">No Metadata Documentation available.</param>
        /// <param name="sessionID">No Metadata Documentation available.</param>
        /// <param name="currentObjectName">No Metadata Documentation available.</param>
        /// <param name="referenceID">No Metadata Documentation available.</param>
        /// <param name="objectConvertFrom">No Metadata Documentation available.</param>
        public ObjectResult<SP_GetCartProductDetail1_Result> SP_GetCartProductDetail1(global::System.String productIDs, Nullable<global::System.Int64> maxSeqence, global::System.String sessionID, global::System.String currentObjectName, Nullable<global::System.Int64> referenceID, global::System.String objectConvertFrom)
        {
            ObjectParameter productIDsParameter;
            if (productIDs != null)
            {
                productIDsParameter = new ObjectParameter("ProductIDs", productIDs);
            }
            else
            {
                productIDsParameter = new ObjectParameter("ProductIDs", typeof(global::System.String));
            }
    
            ObjectParameter maxSeqenceParameter;
            if (maxSeqence.HasValue)
            {
                maxSeqenceParameter = new ObjectParameter("MaxSeqence", maxSeqence);
            }
            else
            {
                maxSeqenceParameter = new ObjectParameter("MaxSeqence", typeof(global::System.Int64));
            }
    
            ObjectParameter sessionIDParameter;
            if (sessionID != null)
            {
                sessionIDParameter = new ObjectParameter("SessionID", sessionID);
            }
            else
            {
                sessionIDParameter = new ObjectParameter("SessionID", typeof(global::System.String));
            }
    
            ObjectParameter currentObjectNameParameter;
            if (currentObjectName != null)
            {
                currentObjectNameParameter = new ObjectParameter("CurrentObjectName", currentObjectName);
            }
            else
            {
                currentObjectNameParameter = new ObjectParameter("CurrentObjectName", typeof(global::System.String));
            }
    
            ObjectParameter referenceIDParameter;
            if (referenceID.HasValue)
            {
                referenceIDParameter = new ObjectParameter("ReferenceID", referenceID);
            }
            else
            {
                referenceIDParameter = new ObjectParameter("ReferenceID", typeof(global::System.Int64));
            }
    
            ObjectParameter objectConvertFromParameter;
            if (objectConvertFrom != null)
            {
                objectConvertFromParameter = new ObjectParameter("ObjectConvertFrom", objectConvertFrom);
            }
            else
            {
                objectConvertFromParameter = new ObjectParameter("ObjectConvertFrom", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<SP_GetCartProductDetail1_Result>("SP_GetCartProductDetail1", productIDsParameter, maxSeqenceParameter, sessionIDParameter, currentObjectNameParameter, referenceIDParameter, objectConvertFromParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BISPL_CRMDBModel", Name="TempData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TempData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TempData object.
        /// </summary>
        /// <param name="tempDataID">Initial value of the TempDataID property.</param>
        /// <param name="data">Initial value of the Data property.</param>
        /// <param name="lastUpdated">Initial value of the LastUpdated property.</param>
        /// <param name="sessionID">Initial value of the SessionID property.</param>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="objectName">Initial value of the ObjectName property.</param>
        /// <param name="tableName">Initial value of the TableName property.</param>
        public static TempData CreateTempData(global::System.Int32 tempDataID, global::System.String data, global::System.DateTime lastUpdated, global::System.String sessionID, global::System.String userID, global::System.String objectName, global::System.String tableName)
        {
            TempData tempData = new TempData();
            tempData.TempDataID = tempDataID;
            tempData.Data = data;
            tempData.LastUpdated = lastUpdated;
            tempData.SessionID = sessionID;
            tempData.UserID = userID;
            tempData.ObjectName = objectName;
            tempData.TableName = tableName;
            return tempData;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TempDataID
        {
            get
            {
                return _TempDataID;
            }
            set
            {
                if (_TempDataID != value)
                {
                    OnTempDataIDChanging(value);
                    ReportPropertyChanging("TempDataID");
                    _TempDataID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TempDataID");
                    OnTempDataIDChanged();
                }
            }
        }
        private global::System.Int32 _TempDataID;
        partial void OnTempDataIDChanging(global::System.Int32 value);
        partial void OnTempDataIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Data
        {
            get
            {
                return _Data;
            }
            set
            {
                OnDataChanging(value);
                ReportPropertyChanging("Data");
                _Data = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Data");
                OnDataChanged();
            }
        }
        private global::System.String _Data;
        partial void OnDataChanging(global::System.String value);
        partial void OnDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String XmlData
        {
            get
            {
                return _XmlData;
            }
            set
            {
                OnXmlDataChanging(value);
                ReportPropertyChanging("XmlData");
                _XmlData = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("XmlData");
                OnXmlDataChanged();
            }
        }
        private global::System.String _XmlData;
        partial void OnXmlDataChanging(global::System.String value);
        partial void OnXmlDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastUpdated
        {
            get
            {
                return _LastUpdated;
            }
            set
            {
                OnLastUpdatedChanging(value);
                ReportPropertyChanging("LastUpdated");
                _LastUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdated");
                OnLastUpdatedChanged();
            }
        }
        private global::System.DateTime _LastUpdated;
        partial void OnLastUpdatedChanging(global::System.DateTime value);
        partial void OnLastUpdatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SessionID
        {
            get
            {
                return _SessionID;
            }
            set
            {
                OnSessionIDChanging(value);
                ReportPropertyChanging("SessionID");
                _SessionID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SessionID");
                OnSessionIDChanged();
            }
        }
        private global::System.String _SessionID;
        partial void OnSessionIDChanging(global::System.String value);
        partial void OnSessionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private global::System.String _UserID;
        partial void OnUserIDChanging(global::System.String value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ObjectName
        {
            get
            {
                return _ObjectName;
            }
            set
            {
                OnObjectNameChanging(value);
                ReportPropertyChanging("ObjectName");
                _ObjectName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ObjectName");
                OnObjectNameChanged();
            }
        }
        private global::System.String _ObjectName;
        partial void OnObjectNameChanging(global::System.String value);
        partial void OnObjectNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TableName
        {
            get
            {
                return _TableName;
            }
            set
            {
                OnTableNameChanging(value);
                ReportPropertyChanging("TableName");
                _TableName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TableName");
                OnTableNameChanged();
            }
        }
        private global::System.String _TableName;
        partial void OnTableNameChanging(global::System.String value);
        partial void OnTableNameChanged();

        #endregion

    
    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="BISPL_CRMDBModel", Name="SP_GetCartProductDetail_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class SP_GetCartProductDetail_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SP_GetCartProductDetail_Result object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="objectName">Initial value of the ObjectName property.</param>
        /// <param name="referenceID">Initial value of the ReferenceID property.</param>
        /// <param name="productID">Initial value of the ProductID property.</param>
        /// <param name="productName">Initial value of the ProductName property.</param>
        /// <param name="uOMID">Initial value of the UOMID property.</param>
        /// <param name="uOM">Initial value of the UOM property.</param>
        /// <param name="perUnitDiscount">Initial value of the PerUnitDiscount property.</param>
        /// <param name="isDiscountPercent">Initial value of the IsDiscountPercent property.</param>
        /// <param name="discountID">Initial value of the DiscountID property.</param>
        /// <param name="quantity">Initial value of the Quantity property.</param>
        /// <param name="remark">Initial value of the Remark property.</param>
        public static SP_GetCartProductDetail_Result CreateSP_GetCartProductDetail_Result(global::System.Int32 id, global::System.String objectName, global::System.Int32 referenceID, global::System.Int64 productID, global::System.String productName, global::System.Int64 uOMID, global::System.String uOM, global::System.Decimal perUnitDiscount, global::System.String isDiscountPercent, global::System.Int32 discountID, global::System.Decimal quantity, global::System.String remark)
        {
            SP_GetCartProductDetail_Result sP_GetCartProductDetail_Result = new SP_GetCartProductDetail_Result();
            sP_GetCartProductDetail_Result.ID = id;
            sP_GetCartProductDetail_Result.ObjectName = objectName;
            sP_GetCartProductDetail_Result.ReferenceID = referenceID;
            sP_GetCartProductDetail_Result.ProductID = productID;
            sP_GetCartProductDetail_Result.ProductName = productName;
            sP_GetCartProductDetail_Result.UOMID = uOMID;
            sP_GetCartProductDetail_Result.UOM = uOM;
            sP_GetCartProductDetail_Result.PerUnitDiscount = perUnitDiscount;
            sP_GetCartProductDetail_Result.IsDiscountPercent = isDiscountPercent;
            sP_GetCartProductDetail_Result.DiscountID = discountID;
            sP_GetCartProductDetail_Result.Quantity = quantity;
            sP_GetCartProductDetail_Result.Remark = remark;
            return sP_GetCartProductDetail_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                OnIDChanging(value);
                ReportPropertyChanging("ID");
                _ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID");
                OnIDChanged();
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ObjectName
        {
            get
            {
                return _ObjectName;
            }
            set
            {
                OnObjectNameChanging(value);
                ReportPropertyChanging("ObjectName");
                _ObjectName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ObjectName");
                OnObjectNameChanged();
            }
        }
        private global::System.String _ObjectName;
        partial void OnObjectNameChanging(global::System.String value);
        partial void OnObjectNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReferenceID
        {
            get
            {
                return _ReferenceID;
            }
            set
            {
                OnReferenceIDChanging(value);
                ReportPropertyChanging("ReferenceID");
                _ReferenceID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReferenceID");
                OnReferenceIDChanged();
            }
        }
        private global::System.Int32 _ReferenceID;
        partial void OnReferenceIDChanging(global::System.Int32 value);
        partial void OnReferenceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Sequence
        {
            get
            {
                return _Sequence;
            }
            set
            {
                OnSequenceChanging(value);
                ReportPropertyChanging("Sequence");
                _Sequence = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sequence");
                OnSequenceChanged();
            }
        }
        private Nullable<global::System.Int64> _Sequence;
        partial void OnSequenceChanging(Nullable<global::System.Int64> value);
        partial void OnSequenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ProductID
        {
            get
            {
                return _ProductID;
            }
            set
            {
                OnProductIDChanging(value);
                ReportPropertyChanging("ProductID");
                _ProductID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductID");
                OnProductIDChanged();
            }
        }
        private global::System.Int64 _ProductID;
        partial void OnProductIDChanging(global::System.Int64 value);
        partial void OnProductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductCode
        {
            get
            {
                return _ProductCode;
            }
            set
            {
                OnProductCodeChanging(value);
                ReportPropertyChanging("ProductCode");
                _ProductCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductCode");
                OnProductCodeChanged();
            }
        }
        private global::System.String _ProductCode;
        partial void OnProductCodeChanging(global::System.String value);
        partial void OnProductCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductName
        {
            get
            {
                return _ProductName;
            }
            set
            {
                OnProductNameChanging(value);
                ReportPropertyChanging("ProductName");
                _ProductName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProductName");
                OnProductNameChanged();
            }
        }
        private global::System.String _ProductName;
        partial void OnProductNameChanging(global::System.String value);
        partial void OnProductNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductDescription
        {
            get
            {
                return _ProductDescription;
            }
            set
            {
                OnProductDescriptionChanging(value);
                ReportPropertyChanging("ProductDescription");
                _ProductDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductDescription");
                OnProductDescriptionChanged();
            }
        }
        private global::System.String _ProductDescription;
        partial void OnProductDescriptionChanging(global::System.String value);
        partial void OnProductDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UOMID
        {
            get
            {
                return _UOMID;
            }
            set
            {
                OnUOMIDChanging(value);
                ReportPropertyChanging("UOMID");
                _UOMID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UOMID");
                OnUOMIDChanged();
            }
        }
        private global::System.Int64 _UOMID;
        partial void OnUOMIDChanging(global::System.Int64 value);
        partial void OnUOMIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UOM
        {
            get
            {
                return _UOM;
            }
            set
            {
                OnUOMChanging(value);
                ReportPropertyChanging("UOM");
                _UOM = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UOM");
                OnUOMChanged();
            }
        }
        private global::System.String _UOM;
        partial void OnUOMChanging(global::System.String value);
        partial void OnUOMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ProductPrice
        {
            get
            {
                return _ProductPrice;
            }
            set
            {
                OnProductPriceChanging(value);
                ReportPropertyChanging("ProductPrice");
                _ProductPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductPrice");
                OnProductPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _ProductPrice;
        partial void OnProductPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnProductPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PerUnitDiscount
        {
            get
            {
                return _PerUnitDiscount;
            }
            set
            {
                OnPerUnitDiscountChanging(value);
                ReportPropertyChanging("PerUnitDiscount");
                _PerUnitDiscount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PerUnitDiscount");
                OnPerUnitDiscountChanged();
            }
        }
        private global::System.Decimal _PerUnitDiscount;
        partial void OnPerUnitDiscountChanging(global::System.Decimal value);
        partial void OnPerUnitDiscountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IsDiscountPercent
        {
            get
            {
                return _IsDiscountPercent;
            }
            set
            {
                OnIsDiscountPercentChanging(value);
                ReportPropertyChanging("IsDiscountPercent");
                _IsDiscountPercent = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IsDiscountPercent");
                OnIsDiscountPercentChanged();
            }
        }
        private global::System.String _IsDiscountPercent;
        partial void OnIsDiscountPercentChanging(global::System.String value);
        partial void OnIsDiscountPercentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DiscountID
        {
            get
            {
                return _DiscountID;
            }
            set
            {
                OnDiscountIDChanging(value);
                ReportPropertyChanging("DiscountID");
                _DiscountID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DiscountID");
                OnDiscountIDChanged();
            }
        }
        private global::System.Int32 _DiscountID;
        partial void OnDiscountIDChanging(global::System.Int32 value);
        partial void OnDiscountIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RateAfterDiscount
        {
            get
            {
                return _RateAfterDiscount;
            }
            set
            {
                OnRateAfterDiscountChanging(value);
                ReportPropertyChanging("RateAfterDiscount");
                _RateAfterDiscount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RateAfterDiscount");
                OnRateAfterDiscountChanged();
            }
        }
        private Nullable<global::System.Decimal> _RateAfterDiscount;
        partial void OnRateAfterDiscountChanging(Nullable<global::System.Decimal> value);
        partial void OnRateAfterDiscountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                OnQuantityChanging(value);
                ReportPropertyChanging("Quantity");
                _Quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quantity");
                OnQuantityChanged();
            }
        }
        private global::System.Decimal _Quantity;
        partial void OnQuantityChanging(global::System.Decimal value);
        partial void OnQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> AmountAfterDiscount
        {
            get
            {
                return _AmountAfterDiscount;
            }
            set
            {
                OnAmountAfterDiscountChanging(value);
                ReportPropertyChanging("AmountAfterDiscount");
                _AmountAfterDiscount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AmountAfterDiscount");
                OnAmountAfterDiscountChanged();
            }
        }
        private Nullable<global::System.Decimal> _AmountAfterDiscount;
        partial void OnAmountAfterDiscountChanging(Nullable<global::System.Decimal> value);
        partial void OnAmountAfterDiscountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TotalTaxAmount
        {
            get
            {
                return _TotalTaxAmount;
            }
            set
            {
                OnTotalTaxAmountChanging(value);
                ReportPropertyChanging("TotalTaxAmount");
                _TotalTaxAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalTaxAmount");
                OnTotalTaxAmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _TotalTaxAmount;
        partial void OnTotalTaxAmountChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalTaxAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> AmountAfterTax
        {
            get
            {
                return _AmountAfterTax;
            }
            set
            {
                OnAmountAfterTaxChanging(value);
                ReportPropertyChanging("AmountAfterTax");
                _AmountAfterTax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AmountAfterTax");
                OnAmountAfterTaxChanged();
            }
        }
        private Nullable<global::System.Decimal> _AmountAfterTax;
        partial void OnAmountAfterTaxChanging(Nullable<global::System.Decimal> value);
        partial void OnAmountAfterTaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                OnRemarkChanging(value);
                ReportPropertyChanging("Remark");
                _Remark = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Remark");
                OnRemarkChanged();
            }
        }
        private global::System.String _Remark;
        partial void OnRemarkChanging(global::System.String value);
        partial void OnRemarkChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="BISPL_CRMDBModel", Name="SP_GetCartProductDetail1_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class SP_GetCartProductDetail1_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SP_GetCartProductDetail1_Result object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="objectName">Initial value of the ObjectName property.</param>
        /// <param name="referenceID">Initial value of the ReferenceID property.</param>
        /// <param name="productID">Initial value of the ProductID property.</param>
        /// <param name="productName">Initial value of the ProductName property.</param>
        /// <param name="uOMID">Initial value of the UOMID property.</param>
        /// <param name="uOM">Initial value of the UOM property.</param>
        /// <param name="perUnitDiscount">Initial value of the PerUnitDiscount property.</param>
        /// <param name="isDiscountPercent">Initial value of the IsDiscountPercent property.</param>
        /// <param name="discountID">Initial value of the DiscountID property.</param>
        /// <param name="quantity">Initial value of the Quantity property.</param>
        /// <param name="remark">Initial value of the Remark property.</param>
        public static SP_GetCartProductDetail1_Result CreateSP_GetCartProductDetail1_Result(global::System.Int32 id, global::System.String objectName, global::System.Int32 referenceID, global::System.Int64 productID, global::System.String productName, global::System.Int64 uOMID, global::System.String uOM, global::System.Decimal perUnitDiscount, global::System.String isDiscountPercent, global::System.Int32 discountID, global::System.Decimal quantity, global::System.String remark)
        {
            SP_GetCartProductDetail1_Result sP_GetCartProductDetail1_Result = new SP_GetCartProductDetail1_Result();
            sP_GetCartProductDetail1_Result.ID = id;
            sP_GetCartProductDetail1_Result.ObjectName = objectName;
            sP_GetCartProductDetail1_Result.ReferenceID = referenceID;
            sP_GetCartProductDetail1_Result.ProductID = productID;
            sP_GetCartProductDetail1_Result.ProductName = productName;
            sP_GetCartProductDetail1_Result.UOMID = uOMID;
            sP_GetCartProductDetail1_Result.UOM = uOM;
            sP_GetCartProductDetail1_Result.PerUnitDiscount = perUnitDiscount;
            sP_GetCartProductDetail1_Result.IsDiscountPercent = isDiscountPercent;
            sP_GetCartProductDetail1_Result.DiscountID = discountID;
            sP_GetCartProductDetail1_Result.Quantity = quantity;
            sP_GetCartProductDetail1_Result.Remark = remark;
            return sP_GetCartProductDetail1_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                OnIDChanging(value);
                ReportPropertyChanging("ID");
                _ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID");
                OnIDChanged();
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ObjectName
        {
            get
            {
                return _ObjectName;
            }
            set
            {
                OnObjectNameChanging(value);
                ReportPropertyChanging("ObjectName");
                _ObjectName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ObjectName");
                OnObjectNameChanged();
            }
        }
        private global::System.String _ObjectName;
        partial void OnObjectNameChanging(global::System.String value);
        partial void OnObjectNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReferenceID
        {
            get
            {
                return _ReferenceID;
            }
            set
            {
                OnReferenceIDChanging(value);
                ReportPropertyChanging("ReferenceID");
                _ReferenceID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReferenceID");
                OnReferenceIDChanged();
            }
        }
        private global::System.Int32 _ReferenceID;
        partial void OnReferenceIDChanging(global::System.Int32 value);
        partial void OnReferenceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Sequence
        {
            get
            {
                return _Sequence;
            }
            set
            {
                OnSequenceChanging(value);
                ReportPropertyChanging("Sequence");
                _Sequence = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sequence");
                OnSequenceChanged();
            }
        }
        private Nullable<global::System.Int64> _Sequence;
        partial void OnSequenceChanging(Nullable<global::System.Int64> value);
        partial void OnSequenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ProductID
        {
            get
            {
                return _ProductID;
            }
            set
            {
                OnProductIDChanging(value);
                ReportPropertyChanging("ProductID");
                _ProductID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductID");
                OnProductIDChanged();
            }
        }
        private global::System.Int64 _ProductID;
        partial void OnProductIDChanging(global::System.Int64 value);
        partial void OnProductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductCode
        {
            get
            {
                return _ProductCode;
            }
            set
            {
                OnProductCodeChanging(value);
                ReportPropertyChanging("ProductCode");
                _ProductCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductCode");
                OnProductCodeChanged();
            }
        }
        private global::System.String _ProductCode;
        partial void OnProductCodeChanging(global::System.String value);
        partial void OnProductCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductName
        {
            get
            {
                return _ProductName;
            }
            set
            {
                OnProductNameChanging(value);
                ReportPropertyChanging("ProductName");
                _ProductName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProductName");
                OnProductNameChanged();
            }
        }
        private global::System.String _ProductName;
        partial void OnProductNameChanging(global::System.String value);
        partial void OnProductNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductDescription
        {
            get
            {
                return _ProductDescription;
            }
            set
            {
                OnProductDescriptionChanging(value);
                ReportPropertyChanging("ProductDescription");
                _ProductDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductDescription");
                OnProductDescriptionChanged();
            }
        }
        private global::System.String _ProductDescription;
        partial void OnProductDescriptionChanging(global::System.String value);
        partial void OnProductDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UOMID
        {
            get
            {
                return _UOMID;
            }
            set
            {
                OnUOMIDChanging(value);
                ReportPropertyChanging("UOMID");
                _UOMID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UOMID");
                OnUOMIDChanged();
            }
        }
        private global::System.Int64 _UOMID;
        partial void OnUOMIDChanging(global::System.Int64 value);
        partial void OnUOMIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UOM
        {
            get
            {
                return _UOM;
            }
            set
            {
                OnUOMChanging(value);
                ReportPropertyChanging("UOM");
                _UOM = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UOM");
                OnUOMChanged();
            }
        }
        private global::System.String _UOM;
        partial void OnUOMChanging(global::System.String value);
        partial void OnUOMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ProductPrice
        {
            get
            {
                return _ProductPrice;
            }
            set
            {
                OnProductPriceChanging(value);
                ReportPropertyChanging("ProductPrice");
                _ProductPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductPrice");
                OnProductPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _ProductPrice;
        partial void OnProductPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnProductPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PerUnitDiscount
        {
            get
            {
                return _PerUnitDiscount;
            }
            set
            {
                OnPerUnitDiscountChanging(value);
                ReportPropertyChanging("PerUnitDiscount");
                _PerUnitDiscount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PerUnitDiscount");
                OnPerUnitDiscountChanged();
            }
        }
        private global::System.Decimal _PerUnitDiscount;
        partial void OnPerUnitDiscountChanging(global::System.Decimal value);
        partial void OnPerUnitDiscountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IsDiscountPercent
        {
            get
            {
                return _IsDiscountPercent;
            }
            set
            {
                OnIsDiscountPercentChanging(value);
                ReportPropertyChanging("IsDiscountPercent");
                _IsDiscountPercent = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IsDiscountPercent");
                OnIsDiscountPercentChanged();
            }
        }
        private global::System.String _IsDiscountPercent;
        partial void OnIsDiscountPercentChanging(global::System.String value);
        partial void OnIsDiscountPercentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DiscountID
        {
            get
            {
                return _DiscountID;
            }
            set
            {
                OnDiscountIDChanging(value);
                ReportPropertyChanging("DiscountID");
                _DiscountID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DiscountID");
                OnDiscountIDChanged();
            }
        }
        private global::System.Int32 _DiscountID;
        partial void OnDiscountIDChanging(global::System.Int32 value);
        partial void OnDiscountIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RateAfterDiscount
        {
            get
            {
                return _RateAfterDiscount;
            }
            set
            {
                OnRateAfterDiscountChanging(value);
                ReportPropertyChanging("RateAfterDiscount");
                _RateAfterDiscount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RateAfterDiscount");
                OnRateAfterDiscountChanged();
            }
        }
        private Nullable<global::System.Decimal> _RateAfterDiscount;
        partial void OnRateAfterDiscountChanging(Nullable<global::System.Decimal> value);
        partial void OnRateAfterDiscountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                OnQuantityChanging(value);
                ReportPropertyChanging("Quantity");
                _Quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quantity");
                OnQuantityChanged();
            }
        }
        private global::System.Decimal _Quantity;
        partial void OnQuantityChanging(global::System.Decimal value);
        partial void OnQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> AmountAfterDiscount
        {
            get
            {
                return _AmountAfterDiscount;
            }
            set
            {
                OnAmountAfterDiscountChanging(value);
                ReportPropertyChanging("AmountAfterDiscount");
                _AmountAfterDiscount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AmountAfterDiscount");
                OnAmountAfterDiscountChanged();
            }
        }
        private Nullable<global::System.Decimal> _AmountAfterDiscount;
        partial void OnAmountAfterDiscountChanging(Nullable<global::System.Decimal> value);
        partial void OnAmountAfterDiscountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TotalTaxAmount
        {
            get
            {
                return _TotalTaxAmount;
            }
            set
            {
                OnTotalTaxAmountChanging(value);
                ReportPropertyChanging("TotalTaxAmount");
                _TotalTaxAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalTaxAmount");
                OnTotalTaxAmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _TotalTaxAmount;
        partial void OnTotalTaxAmountChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalTaxAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> AmountAfterTax
        {
            get
            {
                return _AmountAfterTax;
            }
            set
            {
                OnAmountAfterTaxChanging(value);
                ReportPropertyChanging("AmountAfterTax");
                _AmountAfterTax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AmountAfterTax");
                OnAmountAfterTaxChanged();
            }
        }
        private Nullable<global::System.Decimal> _AmountAfterTax;
        partial void OnAmountAfterTaxChanging(Nullable<global::System.Decimal> value);
        partial void OnAmountAfterTaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                OnRemarkChanging(value);
                ReportPropertyChanging("Remark");
                _Remark = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Remark");
                OnRemarkChanged();
            }
        }
        private global::System.String _Remark;
        partial void OnRemarkChanging(global::System.String value);
        partial void OnRemarkChanged();

        #endregion

    }

    #endregion

    
}
