//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrilliantWMS.ContactPerson {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ContactPerson.iUC_ContactPerson")]
    public interface iUC_ContactPerson {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iUC_ContactPerson/GetContactPersonByReferenceId", ReplyAction="http://tempuri.org/iUC_ContactPerson/GetContactPersonByReferenceIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        BrilliantWMS.ContactPerson.SP_GetContactPersonsByReferenceID_Result[] GetContactPersonByReferenceId(string saveobjectName, long ReferenceID, string paraSessionID, string paraUserID, string SenderObject, long SenderID, string currentformid, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iUC_ContactPerson/InsertIntoTemp", ReplyAction="http://tempuri.org/iUC_ContactPerson/InsertIntoTempResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        BrilliantWMS.ContactPerson.SP_GetContactPersonsByReferenceID_Result[] InsertIntoTemp(BrilliantWMS.ContactPerson.SP_GetContactPersonsByReferenceID_Result ContactPerson, string paraSessionID, string paraUserID, string currentformid, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iUC_ContactPerson/ClearTempDataFromDB", ReplyAction="http://tempuri.org/iUC_ContactPerson/ClearTempDataFromDBResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        void ClearTempDataFromDB(string paraSessionID, string paraUserID, string currentformid, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iUC_ContactPerson/SetValuesToTempData_onChange", ReplyAction="http://tempuri.org/iUC_ContactPerson/SetValuesToTempData_onChangeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        BrilliantWMS.ContactPerson.SP_GetContactPersonsByReferenceID_Result[] SetValuesToTempData_onChange(string paraSessionID, string paraUserID, string currentformid, int paraSequence, BrilliantWMS.ContactPerson.SP_GetContactPersonsByReferenceID_Result paraInput, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iUC_ContactPerson/FinalSaveToDBtAddToContactPerson", ReplyAction="http://tempuri.org/iUC_ContactPerson/FinalSaveToDBtAddToContactPersonResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        void FinalSaveToDBtAddToContactPerson(string paraSessionID, string currentformid, long paraReferenceID, string paraUserID, string paraSaveObjectName, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iUC_ContactPerson/GetContactDetailFromTempTableBySequence", ReplyAction="http://tempuri.org/iUC_ContactPerson/GetContactDetailFromTempTableBySequenceRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        BrilliantWMS.ContactPerson.SP_GetContactPersonsByReferenceID_Result GetContactDetailFromTempTableBySequence(string paraSessionID, string paraUserID, string currentFormID, int paraSequence, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iUC_ContactPerson/GetContactPersonByName", ReplyAction="http://tempuri.org/iUC_ContactPerson/GetContactPersonByNameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        string GetContactPersonByName(string paraSessionID, string Name, string ContactType, string paraUserID, string currentFormID, string[] conn);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SP_GetContactPersonsByReferenceID_Result : ComplexObject {
        
        private string objectNameField;
        
        private long referenceIDField;
        
        private long customerHeadIDField;
        
        private long sequenceField;
        
        private string nameField;
        
        private string departmentField;
        
        private string designationField;
        
        private string emailIDField;
        
        private string officeNoField;
        
        private string mobileNoField;
        
        private long contactTypeIDField;
        
        private string contactTypeField;
        
        private string interestedInField;
        
        private string hobbiesField;
        
        private string facebookIDField;
        
        private string facebookPasswordField;
        
        private string twitterIDField;
        
        private string twitterPasswordField;
        
        private string otherIDField;
        
        private string highestQualificationField;
        
        private string collegeOrUniversityField;
        
        private string highSchoolField;
        
        private string remarkField;
        
        private string activeField;
        
        private string createdByField;
        
        private System.DateTime creationDateField;
        
        private string lastModifiedByField;
        
        private System.Nullable<System.DateTime> lastModifiedDateField;
        
        private long companyIDField;
        
        private string selectedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
                this.RaisePropertyChanged("ObjectName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long ReferenceID {
            get {
                return this.referenceIDField;
            }
            set {
                this.referenceIDField = value;
                this.RaisePropertyChanged("ReferenceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long CustomerHeadID {
            get {
                return this.customerHeadIDField;
            }
            set {
                this.customerHeadIDField = value;
                this.RaisePropertyChanged("CustomerHeadID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
                this.RaisePropertyChanged("Sequence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
                this.RaisePropertyChanged("Department");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Designation {
            get {
                return this.designationField;
            }
            set {
                this.designationField = value;
                this.RaisePropertyChanged("Designation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string EmailID {
            get {
                return this.emailIDField;
            }
            set {
                this.emailIDField = value;
                this.RaisePropertyChanged("EmailID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string OfficeNo {
            get {
                return this.officeNoField;
            }
            set {
                this.officeNoField = value;
                this.RaisePropertyChanged("OfficeNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string MobileNo {
            get {
                return this.mobileNoField;
            }
            set {
                this.mobileNoField = value;
                this.RaisePropertyChanged("MobileNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public long ContactTypeID {
            get {
                return this.contactTypeIDField;
            }
            set {
                this.contactTypeIDField = value;
                this.RaisePropertyChanged("ContactTypeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ContactType {
            get {
                return this.contactTypeField;
            }
            set {
                this.contactTypeField = value;
                this.RaisePropertyChanged("ContactType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string InterestedIn {
            get {
                return this.interestedInField;
            }
            set {
                this.interestedInField = value;
                this.RaisePropertyChanged("InterestedIn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Hobbies {
            get {
                return this.hobbiesField;
            }
            set {
                this.hobbiesField = value;
                this.RaisePropertyChanged("Hobbies");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string FacebookID {
            get {
                return this.facebookIDField;
            }
            set {
                this.facebookIDField = value;
                this.RaisePropertyChanged("FacebookID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string FacebookPassword {
            get {
                return this.facebookPasswordField;
            }
            set {
                this.facebookPasswordField = value;
                this.RaisePropertyChanged("FacebookPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string TwitterID {
            get {
                return this.twitterIDField;
            }
            set {
                this.twitterIDField = value;
                this.RaisePropertyChanged("TwitterID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string TwitterPassword {
            get {
                return this.twitterPasswordField;
            }
            set {
                this.twitterPasswordField = value;
                this.RaisePropertyChanged("TwitterPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string OtherID {
            get {
                return this.otherIDField;
            }
            set {
                this.otherIDField = value;
                this.RaisePropertyChanged("OtherID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string HighestQualification {
            get {
                return this.highestQualificationField;
            }
            set {
                this.highestQualificationField = value;
                this.RaisePropertyChanged("HighestQualification");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string CollegeOrUniversity {
            get {
                return this.collegeOrUniversityField;
            }
            set {
                this.collegeOrUniversityField = value;
                this.RaisePropertyChanged("CollegeOrUniversity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string HighSchool {
            get {
                return this.highSchoolField;
            }
            set {
                this.highSchoolField = value;
                this.RaisePropertyChanged("HighSchool");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("Remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public System.DateTime CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
                this.RaisePropertyChanged("CreationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string LastModifiedBy {
            get {
                return this.lastModifiedByField;
            }
            set {
                this.lastModifiedByField = value;
                this.RaisePropertyChanged("LastModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public System.Nullable<System.DateTime> LastModifiedDate {
            get {
                return this.lastModifiedDateField;
            }
            set {
                this.lastModifiedDateField = value;
                this.RaisePropertyChanged("LastModifiedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public long CompanyID {
            get {
                return this.companyIDField;
            }
            set {
                this.companyIDField = value;
                this.RaisePropertyChanged("CompanyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string selected {
            get {
                return this.selectedField;
            }
            set {
                this.selectedField = value;
                this.RaisePropertyChanged("selected");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SP_GetContactPersonsByReferenceID_Result))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class ComplexObject : StructuralObject {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComplexObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SP_GetContactPersonsByReferenceID_Result))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class StructuralObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface iUC_ContactPersonChannel : BrilliantWMS.ContactPerson.iUC_ContactPerson, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class iUC_ContactPersonClient : System.ServiceModel.ClientBase<BrilliantWMS.ContactPerson.iUC_ContactPerson>, BrilliantWMS.ContactPerson.iUC_ContactPerson {
        
        public iUC_ContactPersonClient() {
        }
        
        public iUC_ContactPersonClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public iUC_ContactPersonClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iUC_ContactPersonClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iUC_ContactPersonClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BrilliantWMS.ContactPerson.SP_GetContactPersonsByReferenceID_Result[] GetContactPersonByReferenceId(string saveobjectName, long ReferenceID, string paraSessionID, string paraUserID, string SenderObject, long SenderID, string currentformid, string[] conn) {
            return base.Channel.GetContactPersonByReferenceId(saveobjectName, ReferenceID, paraSessionID, paraUserID, SenderObject, SenderID, currentformid, conn);
        }
        
        public BrilliantWMS.ContactPerson.SP_GetContactPersonsByReferenceID_Result[] InsertIntoTemp(BrilliantWMS.ContactPerson.SP_GetContactPersonsByReferenceID_Result ContactPerson, string paraSessionID, string paraUserID, string currentformid, string[] conn) {
            return base.Channel.InsertIntoTemp(ContactPerson, paraSessionID, paraUserID, currentformid, conn);
        }
        
        public void ClearTempDataFromDB(string paraSessionID, string paraUserID, string currentformid, string[] conn) {
            base.Channel.ClearTempDataFromDB(paraSessionID, paraUserID, currentformid, conn);
        }
        
        public BrilliantWMS.ContactPerson.SP_GetContactPersonsByReferenceID_Result[] SetValuesToTempData_onChange(string paraSessionID, string paraUserID, string currentformid, int paraSequence, BrilliantWMS.ContactPerson.SP_GetContactPersonsByReferenceID_Result paraInput, string[] conn) {
            return base.Channel.SetValuesToTempData_onChange(paraSessionID, paraUserID, currentformid, paraSequence, paraInput, conn);
        }
        
        public void FinalSaveToDBtAddToContactPerson(string paraSessionID, string currentformid, long paraReferenceID, string paraUserID, string paraSaveObjectName, string[] conn) {
            base.Channel.FinalSaveToDBtAddToContactPerson(paraSessionID, currentformid, paraReferenceID, paraUserID, paraSaveObjectName, conn);
        }
        
        public BrilliantWMS.ContactPerson.SP_GetContactPersonsByReferenceID_Result GetContactDetailFromTempTableBySequence(string paraSessionID, string paraUserID, string currentFormID, int paraSequence, string[] conn) {
            return base.Channel.GetContactDetailFromTempTableBySequence(paraSessionID, paraUserID, currentFormID, paraSequence, conn);
        }
        
        public string GetContactPersonByName(string paraSessionID, string Name, string ContactType, string paraUserID, string currentFormID, string[] conn) {
            return base.Channel.GetContactPersonByName(paraSessionID, Name, ContactType, paraUserID, currentFormID, conn);
        }
    }
}
