//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrilliantWMS.CycleCountService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CycleCountService.iCycleCount")]
    public interface iCycleCount {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iCycleCount/GetCycleCountMain", ReplyAction="http://tempuri.org/iCycleCount/GetCycleCountMainResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(V_WMS_GetHeadCycleCount[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        BrilliantWMS.CycleCountService.V_WMS_GetHeadCycleCount[] GetCycleCountMain(string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iCycleCount/SaveCycleCounttemp", ReplyAction="http://tempuri.org/iCycleCount/SaveCycleCounttempResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(V_WMS_GetHeadCycleCount[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        long SaveCycleCounttemp(BrilliantWMS.CycleCountService.CycleCountTemp CycleTemp, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iCycleCount/GetCycleCounttempdata", ReplyAction="http://tempuri.org/iCycleCount/GetCycleCounttempdataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(V_WMS_GetHeadCycleCount[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        System.Data.DataSet GetCycleCounttempdata(string Object, long CreatedBy, string SessionID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iCycleCount/GetCycleCountTempDataByLoc", ReplyAction="http://tempuri.org/iCycleCount/GetCycleCountTempDataByLocResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(V_WMS_GetHeadCycleCount[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        System.Data.DataSet GetCycleCountTempDataByLoc(string Object, long CreatedBy, string SessionID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iCycleCount/SaveCycleCountHead", ReplyAction="http://tempuri.org/iCycleCount/SaveCycleCountHeadResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(V_WMS_GetHeadCycleCount[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        long SaveCycleCountHead(BrilliantWMS.CycleCountService.tCycleCountHead CycleHead, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iCycleCount/GetCycleTempDataToInsert", ReplyAction="http://tempuri.org/iCycleCount/GetCycleTempDataToInsertResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(V_WMS_GetHeadCycleCount[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        System.Data.DataSet GetCycleTempDataToInsert(string Object, long CreatedBy, string SessionID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iCycleCount/SaveCyclePlanData", ReplyAction="http://tempuri.org/iCycleCount/SaveCyclePlanDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(V_WMS_GetHeadCycleCount[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        void SaveCyclePlanData(System.Data.DataTable DetailInsertion, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iCycleCount/DeleteCycletempData", ReplyAction="http://tempuri.org/iCycleCount/DeleteCycletempDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(V_WMS_GetHeadCycleCount[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        void DeleteCycletempData(string Object, long CreatedBy, string SessionID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iCycleCount/DeleteCycleTempWithoutObj", ReplyAction="http://tempuri.org/iCycleCount/DeleteCycleTempWithoutObjResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(V_WMS_GetHeadCycleCount[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        void DeleteCycleTempWithoutObj(long CreatedBy, string SessionID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iCycleCount/GetCyleCountHeadByID", ReplyAction="http://tempuri.org/iCycleCount/GetCyleCountHeadByIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(V_WMS_GetHeadCycleCount[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        BrilliantWMS.CycleCountService.tCycleCountHead GetCyleCountHeadByID(long CycleHeadID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iCycleCount/GetLocationID", ReplyAction="http://tempuri.org/iCycleCount/GetLocationIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(V_WMS_GetHeadCycleCount[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        long GetLocationID(string Code, long WarehouseID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iCycleCount/CheckLocInPlann", ReplyAction="http://tempuri.org/iCycleCount/CheckLocInPlannResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(V_WMS_GetHeadCycleCount[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        long CheckLocInPlann(string Object, long CycleHeadID, long ReferenceID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iCycleCount/SaveCycleCount", ReplyAction="http://tempuri.org/iCycleCount/SaveCycleCountResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(V_WMS_GetHeadCycleCount[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        long SaveCycleCount(BrilliantWMS.CycleCountService.tCycleCountDetail cycledetail, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iCycleCount/GetSKUID", ReplyAction="http://tempuri.org/iCycleCount/GetSKUIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(V_WMS_GetHeadCycleCount[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        long GetSKUID(string ProductCode, long WarehouseID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iCycleCount/GetCycleCountDetail", ReplyAction="http://tempuri.org/iCycleCount/GetCycleCountDetailResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(V_WMS_GetHeadCycleCount[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        BrilliantWMS.CycleCountService.tCycleCountDetail[] GetCycleCountDetail(long CycleHeadID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iCycleCount/GetRepeatedCycleCountData", ReplyAction="http://tempuri.org/iCycleCount/GetRepeatedCycleCountDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(V_WMS_GetHeadCycleCount[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        System.Data.DataSet GetRepeatedCycleCountData(long CountHeadID, long SKUID, long LocationID, string BatchCode, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iCycleCount/GetSKUIDBySKUCode", ReplyAction="http://tempuri.org/iCycleCount/GetSKUIDBySKUCodeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(V_WMS_GetHeadCycleCount[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        long GetSKUIDBySKUCode(string ProductCode, long WarehouseID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iCycleCount/GetBatchCodeBySKU", ReplyAction="http://tempuri.org/iCycleCount/GetBatchCodeBySKUResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(V_WMS_GetHeadCycleCount[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        System.Data.DataSet GetBatchCodeBySKU(long SKUId, long LocationID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iCycleCount/GetSystemQtyByBatch", ReplyAction="http://tempuri.org/iCycleCount/GetSystemQtyByBatchResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(V_WMS_GetHeadCycleCount[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        decimal GetSystemQtyByBatch(long SKUId, long LocationID, string BatchCode, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iCycleCount/UpdateStockSkuTransForFromLoc", ReplyAction="http://tempuri.org/iCycleCount/UpdateStockSkuTransForFromLocResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(V_WMS_GetHeadCycleCount[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        void UpdateStockSkuTransForFromLoc(long SKUId, string BatchCode, long LocationID, decimal DiffQty, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iCycleCount/UpdateStocktransToLoc", ReplyAction="http://tempuri.org/iCycleCount/UpdateStocktransToLocResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(V_WMS_GetHeadCycleCount[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        void UpdateStocktransToLoc(long SKUId, string BatchCode, decimal DiffQty, long LocationID, long CreatedBy, long CycleHeadID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iCycleCount/getLocationRemainingQty", ReplyAction="http://tempuri.org/iCycleCount/getLocationRemainingQtyResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(V_WMS_GetHeadCycleCount[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        decimal getLocationRemainingQty(long ID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iCycleCount/getCompanyCustomer", ReplyAction="http://tempuri.org/iCycleCount/getCompanyCustomerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(V_WMS_GetHeadCycleCount[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        System.Data.DataSet getCompanyCustomer(long ID, string[] conn);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class V_WMS_GetHeadCycleCount : EntityObject {
        
        private long idField;
        
        private string titleField;
        
        private string descriptionField;
        
        private System.Nullable<System.DateTime> cycleCountDateField;
        
        private string executiveField;
        
        private string companyField;
        
        private string customerField;
        
        private System.Nullable<long> companyIDField;
        
        private System.Nullable<long> customerIDField;
        
        private string warehouseNameField;
        
        private string statusField;
        
        private string frequencyField;
        
        private string countBasisField;
        
        private string activeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> CycleCountDate {
            get {
                return this.cycleCountDateField;
            }
            set {
                this.cycleCountDateField = value;
                this.RaisePropertyChanged("CycleCountDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Executive {
            get {
                return this.executiveField;
            }
            set {
                this.executiveField = value;
                this.RaisePropertyChanged("Executive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("Company");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
                this.RaisePropertyChanged("Customer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<long> CompanyID {
            get {
                return this.companyIDField;
            }
            set {
                this.companyIDField = value;
                this.RaisePropertyChanged("CompanyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<long> CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("CustomerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string WarehouseName {
            get {
                return this.warehouseNameField;
            }
            set {
                this.warehouseNameField = value;
                this.RaisePropertyChanged("WarehouseName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Frequency {
            get {
                return this.frequencyField;
            }
            set {
                this.frequencyField = value;
                this.RaisePropertyChanged("Frequency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string CountBasis {
            get {
                return this.countBasisField;
            }
            set {
                this.countBasisField = value;
                this.RaisePropertyChanged("CountBasis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tCycleCountHead))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CycleCountTemp))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tCycleCountDetail))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(V_WMS_GetHeadCycleCount))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class EntityObject : StructuralObject {
        
        private EntityKey entityKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EntityKey EntityKey {
            get {
                return this.entityKeyField;
            }
            set {
                this.entityKeyField = value;
                this.RaisePropertyChanged("EntityKey");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityKey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entitySetNameField;
        
        private string entityContainerNameField;
        
        private EntityKeyMember[] entityKeyValuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EntitySetName {
            get {
                return this.entitySetNameField;
            }
            set {
                this.entitySetNameField = value;
                this.RaisePropertyChanged("EntitySetName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EntityContainerName {
            get {
                return this.entityContainerNameField;
            }
            set {
                this.entityContainerNameField = value;
                this.RaisePropertyChanged("EntityContainerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public EntityKeyMember[] EntityKeyValues {
            get {
                return this.entityKeyValuesField;
            }
            set {
                this.entityKeyValuesField = value;
                this.RaisePropertyChanged("EntityKeyValues");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityKeyMember : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private object valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tCycleCountHead))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CycleCountTemp))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tCycleCountDetail))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(V_WMS_GetHeadCycleCount))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class StructuralObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class tCycleCountHead : EntityObject {
        
        private long idField;
        
        private string titleField;
        
        private string descriptionField;
        
        private string exicutiveField;
        
        private System.Nullable<long> createdByField;
        
        private System.Nullable<System.DateTime> creationDateField;
        
        private System.Nullable<long> companyIDField;
        
        private System.Nullable<long> customerIDField;
        
        private string statusField;
        
        private System.Nullable<long> warehouseIDField;
        
        private string frequencyField;
        
        private string countBasisField;
        
        private System.Nullable<System.DateTime> cycleCountDateField;
        
        private string activeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Exicutive {
            get {
                return this.exicutiveField;
            }
            set {
                this.exicutiveField = value;
                this.RaisePropertyChanged("Exicutive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<long> CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
                this.RaisePropertyChanged("CreationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<long> CompanyID {
            get {
                return this.companyIDField;
            }
            set {
                this.companyIDField = value;
                this.RaisePropertyChanged("CompanyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<long> CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("CustomerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<long> WarehouseID {
            get {
                return this.warehouseIDField;
            }
            set {
                this.warehouseIDField = value;
                this.RaisePropertyChanged("WarehouseID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Frequency {
            get {
                return this.frequencyField;
            }
            set {
                this.frequencyField = value;
                this.RaisePropertyChanged("Frequency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string CountBasis {
            get {
                return this.countBasisField;
            }
            set {
                this.countBasisField = value;
                this.RaisePropertyChanged("CountBasis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<System.DateTime> CycleCountDate {
            get {
                return this.cycleCountDateField;
            }
            set {
                this.cycleCountDateField = value;
                this.RaisePropertyChanged("CycleCountDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CycleCountTemp : EntityObject {
        
        private long idField;
        
        private string objectField;
        
        private System.Nullable<long> referenceIDField;
        
        private string sessionIDField;
        
        private System.Nullable<long> createdByField;
        
        private System.Nullable<System.DateTime> creationDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Object {
            get {
                return this.objectField;
            }
            set {
                this.objectField = value;
                this.RaisePropertyChanged("Object");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<long> ReferenceID {
            get {
                return this.referenceIDField;
            }
            set {
                this.referenceIDField = value;
                this.RaisePropertyChanged("ReferenceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
                this.RaisePropertyChanged("SessionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<long> CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
                this.RaisePropertyChanged("CreationDate");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class tCycleCountDetail : EntityObject {
        
        private long idField;
        
        private System.Nullable<long> countHeadIDField;
        
        private string productCodeField;
        
        private string locationCodeField;
        
        private System.Nullable<decimal> qtyBalanceField;
        
        private System.Nullable<decimal> actualQtyField;
        
        private System.Nullable<decimal> adjustmentQtyField;
        
        private string remarkField;
        
        private string createdByField;
        
        private System.Nullable<System.DateTime> creationDateField;
        
        private string adjustLocationField;
        
        private System.Nullable<decimal> diffQtyField;
        
        private System.Nullable<long> sKUIDField;
        
        private System.Nullable<long> locationIDField;
        
        private string batchCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<long> CountHeadID {
            get {
                return this.countHeadIDField;
            }
            set {
                this.countHeadIDField = value;
                this.RaisePropertyChanged("CountHeadID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ProductCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
                this.RaisePropertyChanged("ProductCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LocationCode {
            get {
                return this.locationCodeField;
            }
            set {
                this.locationCodeField = value;
                this.RaisePropertyChanged("LocationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<decimal> QtyBalance {
            get {
                return this.qtyBalanceField;
            }
            set {
                this.qtyBalanceField = value;
                this.RaisePropertyChanged("QtyBalance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<decimal> ActualQty {
            get {
                return this.actualQtyField;
            }
            set {
                this.actualQtyField = value;
                this.RaisePropertyChanged("ActualQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<decimal> AdjustmentQty {
            get {
                return this.adjustmentQtyField;
            }
            set {
                this.adjustmentQtyField = value;
                this.RaisePropertyChanged("AdjustmentQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("Remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<System.DateTime> CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
                this.RaisePropertyChanged("CreationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string AdjustLocation {
            get {
                return this.adjustLocationField;
            }
            set {
                this.adjustLocationField = value;
                this.RaisePropertyChanged("AdjustLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<decimal> DiffQty {
            get {
                return this.diffQtyField;
            }
            set {
                this.diffQtyField = value;
                this.RaisePropertyChanged("DiffQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<long> SKUID {
            get {
                return this.sKUIDField;
            }
            set {
                this.sKUIDField = value;
                this.RaisePropertyChanged("SKUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<long> LocationID {
            get {
                return this.locationIDField;
            }
            set {
                this.locationIDField = value;
                this.RaisePropertyChanged("LocationID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string BatchCode {
            get {
                return this.batchCodeField;
            }
            set {
                this.batchCodeField = value;
                this.RaisePropertyChanged("BatchCode");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface iCycleCountChannel : BrilliantWMS.CycleCountService.iCycleCount, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class iCycleCountClient : System.ServiceModel.ClientBase<BrilliantWMS.CycleCountService.iCycleCount>, BrilliantWMS.CycleCountService.iCycleCount {
        
        public iCycleCountClient() {
        }
        
        public iCycleCountClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public iCycleCountClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iCycleCountClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iCycleCountClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BrilliantWMS.CycleCountService.V_WMS_GetHeadCycleCount[] GetCycleCountMain(string[] conn) {
            return base.Channel.GetCycleCountMain(conn);
        }
        
        public long SaveCycleCounttemp(BrilliantWMS.CycleCountService.CycleCountTemp CycleTemp, string[] conn) {
            return base.Channel.SaveCycleCounttemp(CycleTemp, conn);
        }
        
        public System.Data.DataSet GetCycleCounttempdata(string Object, long CreatedBy, string SessionID, string[] conn) {
            return base.Channel.GetCycleCounttempdata(Object, CreatedBy, SessionID, conn);
        }
        
        public System.Data.DataSet GetCycleCountTempDataByLoc(string Object, long CreatedBy, string SessionID, string[] conn) {
            return base.Channel.GetCycleCountTempDataByLoc(Object, CreatedBy, SessionID, conn);
        }
        
        public long SaveCycleCountHead(BrilliantWMS.CycleCountService.tCycleCountHead CycleHead, string[] conn) {
            return base.Channel.SaveCycleCountHead(CycleHead, conn);
        }
        
        public System.Data.DataSet GetCycleTempDataToInsert(string Object, long CreatedBy, string SessionID, string[] conn) {
            return base.Channel.GetCycleTempDataToInsert(Object, CreatedBy, SessionID, conn);
        }
        
        public void SaveCyclePlanData(System.Data.DataTable DetailInsertion, string[] conn) {
            base.Channel.SaveCyclePlanData(DetailInsertion, conn);
        }
        
        public void DeleteCycletempData(string Object, long CreatedBy, string SessionID, string[] conn) {
            base.Channel.DeleteCycletempData(Object, CreatedBy, SessionID, conn);
        }
        
        public void DeleteCycleTempWithoutObj(long CreatedBy, string SessionID, string[] conn) {
            base.Channel.DeleteCycleTempWithoutObj(CreatedBy, SessionID, conn);
        }
        
        public BrilliantWMS.CycleCountService.tCycleCountHead GetCyleCountHeadByID(long CycleHeadID, string[] conn) {
            return base.Channel.GetCyleCountHeadByID(CycleHeadID, conn);
        }
        
        public long GetLocationID(string Code, long WarehouseID, string[] conn) {
            return base.Channel.GetLocationID(Code, WarehouseID, conn);
        }
        
        public long CheckLocInPlann(string Object, long CycleHeadID, long ReferenceID, string[] conn) {
            return base.Channel.CheckLocInPlann(Object, CycleHeadID, ReferenceID, conn);
        }
        
        public long SaveCycleCount(BrilliantWMS.CycleCountService.tCycleCountDetail cycledetail, string[] conn) {
            return base.Channel.SaveCycleCount(cycledetail, conn);
        }
        
        public long GetSKUID(string ProductCode, long WarehouseID, string[] conn) {
            return base.Channel.GetSKUID(ProductCode, WarehouseID, conn);
        }
        
        public BrilliantWMS.CycleCountService.tCycleCountDetail[] GetCycleCountDetail(long CycleHeadID, string[] conn) {
            return base.Channel.GetCycleCountDetail(CycleHeadID, conn);
        }
        
        public System.Data.DataSet GetRepeatedCycleCountData(long CountHeadID, long SKUID, long LocationID, string BatchCode, string[] conn) {
            return base.Channel.GetRepeatedCycleCountData(CountHeadID, SKUID, LocationID, BatchCode, conn);
        }
        
        public long GetSKUIDBySKUCode(string ProductCode, long WarehouseID, string[] conn) {
            return base.Channel.GetSKUIDBySKUCode(ProductCode, WarehouseID, conn);
        }
        
        public System.Data.DataSet GetBatchCodeBySKU(long SKUId, long LocationID, string[] conn) {
            return base.Channel.GetBatchCodeBySKU(SKUId, LocationID, conn);
        }
        
        public decimal GetSystemQtyByBatch(long SKUId, long LocationID, string BatchCode, string[] conn) {
            return base.Channel.GetSystemQtyByBatch(SKUId, LocationID, BatchCode, conn);
        }
        
        public void UpdateStockSkuTransForFromLoc(long SKUId, string BatchCode, long LocationID, decimal DiffQty, string[] conn) {
            base.Channel.UpdateStockSkuTransForFromLoc(SKUId, BatchCode, LocationID, DiffQty, conn);
        }
        
        public void UpdateStocktransToLoc(long SKUId, string BatchCode, decimal DiffQty, long LocationID, long CreatedBy, long CycleHeadID, string[] conn) {
            base.Channel.UpdateStocktransToLoc(SKUId, BatchCode, DiffQty, LocationID, CreatedBy, CycleHeadID, conn);
        }
        
        public decimal getLocationRemainingQty(long ID, string[] conn) {
            return base.Channel.getLocationRemainingQty(ID, conn);
        }
        
        public System.Data.DataSet getCompanyCustomer(long ID, string[] conn) {
            return base.Channel.getCompanyCustomer(ID, conn);
        }
    }
}
